// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WmsResourcePlanner.Infrastructure.Data;

#nullable disable

namespace WmsResourcePlanner.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("WmsResourcePlanner.Domain.Entities.FocusArea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProgramId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("WorkstreamId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProgramId");

                    b.HasIndex("WorkstreamId");

                    b.ToTable("FocusAreas");
                });

            modelBuilder.Entity("WmsResourcePlanner.Domain.Entities.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("AvailableEndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("AvailableStartDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DefaultCapacityFte")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployeeType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Organization")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PrimaryRoleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProgramId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PrimaryRoleId");

                    b.HasIndex("ProgramId");

                    b.ToTable("People");
                });

            modelBuilder.Entity("WmsResourcePlanner.Domain.Entities.PlanningScenario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBaseline")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProgramId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProgramId");

                    b.ToTable("PlanningScenarios");
                });

            modelBuilder.Entity("WmsResourcePlanner.Domain.Entities.Program", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Programs");
                });

            modelBuilder.Entity("WmsResourcePlanner.Domain.Entities.ResourcePlanLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FocusAreaId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Fte")
                        .HasColumnType("decimal(6,2)");

                    b.Property<DateTime>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PersonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProgramId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScenarioId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TeamTemplateAssignmentId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TemplatePhaseId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WorkstreamId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FocusAreaId");

                    b.HasIndex("PersonId");

                    b.HasIndex("ProgramId");

                    b.HasIndex("RoleId");

                    b.HasIndex("TeamId");

                    b.HasIndex("TeamTemplateAssignmentId");

                    b.HasIndex("TemplatePhaseId");

                    b.HasIndex("WorkstreamId");

                    b.HasIndex("StartDate", "EndDate");

                    b.HasIndex("ScenarioId", "TeamId", "RoleId", "PersonId");

                    b.ToTable("ResourcePlanLines");
                });

            modelBuilder.Entity("WmsResourcePlanner.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProgramId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProgramId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("WmsResourcePlanner.Domain.Entities.Site", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("PlannedGoLiveDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProgramId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Region")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProgramId");

                    b.ToTable("Sites");
                });

            modelBuilder.Entity("WmsResourcePlanner.Domain.Entities.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FocusAreaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProgramId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("TeamType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("WorkstreamId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FocusAreaId");

                    b.HasIndex("ProgramId");

                    b.HasIndex("WorkstreamId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("WmsResourcePlanner.Domain.Entities.TeamRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("DefaultRequiredFte")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("TeamId");

                    b.ToTable("TeamRoles");
                });

            modelBuilder.Entity("WmsResourcePlanner.Domain.Entities.TeamSiteAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("SiteId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SiteId");

                    b.HasIndex("TeamId");

                    b.ToTable("TeamSiteAssignments");
                });

            modelBuilder.Entity("WmsResourcePlanner.Domain.Entities.TeamTemplateAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TemplateId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.HasIndex("TemplateId");

                    b.ToTable("TeamTemplateAssignments");
                });

            modelBuilder.Entity("WmsResourcePlanner.Domain.Entities.Template", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProgramId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProgramId");

                    b.ToTable("Templates");
                });

            modelBuilder.Entity("WmsResourcePlanner.Domain.Entities.TemplatePhase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("TemplateId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId");

                    b.ToTable("TemplatePhases");
                });

            modelBuilder.Entity("WmsResourcePlanner.Domain.Entities.Workstream", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProgramId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProgramId");

                    b.ToTable("Workstreams");
                });

            modelBuilder.Entity("WmsResourcePlanner.Domain.Entities.FocusArea", b =>
                {
                    b.HasOne("WmsResourcePlanner.Domain.Entities.Program", "Program")
                        .WithMany()
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WmsResourcePlanner.Domain.Entities.Workstream", "Workstream")
                        .WithMany("FocusAreas")
                        .HasForeignKey("WorkstreamId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Program");

                    b.Navigation("Workstream");
                });

            modelBuilder.Entity("WmsResourcePlanner.Domain.Entities.Person", b =>
                {
                    b.HasOne("WmsResourcePlanner.Domain.Entities.Role", "PrimaryRole")
                        .WithMany()
                        .HasForeignKey("PrimaryRoleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WmsResourcePlanner.Domain.Entities.Program", "Program")
                        .WithMany("People")
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrimaryRole");

                    b.Navigation("Program");
                });

            modelBuilder.Entity("WmsResourcePlanner.Domain.Entities.PlanningScenario", b =>
                {
                    b.HasOne("WmsResourcePlanner.Domain.Entities.Program", "Program")
                        .WithMany("Scenarios")
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Program");
                });

            modelBuilder.Entity("WmsResourcePlanner.Domain.Entities.ResourcePlanLine", b =>
                {
                    b.HasOne("WmsResourcePlanner.Domain.Entities.FocusArea", "FocusArea")
                        .WithMany("ResourcePlanLines")
                        .HasForeignKey("FocusAreaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WmsResourcePlanner.Domain.Entities.Person", "Person")
                        .WithMany("ResourcePlanLines")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WmsResourcePlanner.Domain.Entities.Program", "Program")
                        .WithMany()
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WmsResourcePlanner.Domain.Entities.Role", "Role")
                        .WithMany("ResourcePlanLines")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WmsResourcePlanner.Domain.Entities.PlanningScenario", "Scenario")
                        .WithMany("ResourcePlanLines")
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WmsResourcePlanner.Domain.Entities.Team", "Team")
                        .WithMany("ResourcePlanLines")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WmsResourcePlanner.Domain.Entities.TeamTemplateAssignment", "TeamTemplateAssignment")
                        .WithMany("ResourcePlanLines")
                        .HasForeignKey("TeamTemplateAssignmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WmsResourcePlanner.Domain.Entities.TemplatePhase", "TemplatePhase")
                        .WithMany("ResourcePlanLines")
                        .HasForeignKey("TemplatePhaseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WmsResourcePlanner.Domain.Entities.Workstream", "Workstream")
                        .WithMany("ResourcePlanLines")
                        .HasForeignKey("WorkstreamId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("FocusArea");

                    b.Navigation("Person");

                    b.Navigation("Program");

                    b.Navigation("Role");

                    b.Navigation("Scenario");

                    b.Navigation("Team");

                    b.Navigation("TeamTemplateAssignment");

                    b.Navigation("TemplatePhase");

                    b.Navigation("Workstream");
                });

            modelBuilder.Entity("WmsResourcePlanner.Domain.Entities.Role", b =>
                {
                    b.HasOne("WmsResourcePlanner.Domain.Entities.Program", "Program")
                        .WithMany("Roles")
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Program");
                });

            modelBuilder.Entity("WmsResourcePlanner.Domain.Entities.Site", b =>
                {
                    b.HasOne("WmsResourcePlanner.Domain.Entities.Program", "Program")
                        .WithMany("Sites")
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Program");
                });

            modelBuilder.Entity("WmsResourcePlanner.Domain.Entities.Team", b =>
                {
                    b.HasOne("WmsResourcePlanner.Domain.Entities.FocusArea", "FocusArea")
                        .WithMany("Teams")
                        .HasForeignKey("FocusAreaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WmsResourcePlanner.Domain.Entities.Program", "Program")
                        .WithMany("Teams")
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WmsResourcePlanner.Domain.Entities.Workstream", "Workstream")
                        .WithMany("Teams")
                        .HasForeignKey("WorkstreamId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("FocusArea");

                    b.Navigation("Program");

                    b.Navigation("Workstream");
                });

            modelBuilder.Entity("WmsResourcePlanner.Domain.Entities.TeamRole", b =>
                {
                    b.HasOne("WmsResourcePlanner.Domain.Entities.Role", "Role")
                        .WithMany("TeamRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WmsResourcePlanner.Domain.Entities.Team", "Team")
                        .WithMany("TeamRoles")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("WmsResourcePlanner.Domain.Entities.TeamSiteAssignment", b =>
                {
                    b.HasOne("WmsResourcePlanner.Domain.Entities.Site", "Site")
                        .WithMany("TeamAssignments")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WmsResourcePlanner.Domain.Entities.Team", "Team")
                        .WithMany("SiteAssignments")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Site");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("WmsResourcePlanner.Domain.Entities.TeamTemplateAssignment", b =>
                {
                    b.HasOne("WmsResourcePlanner.Domain.Entities.Team", "Team")
                        .WithMany("TemplateAssignments")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WmsResourcePlanner.Domain.Entities.Template", "Template")
                        .WithMany("TeamAssignments")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("WmsResourcePlanner.Domain.Entities.Template", b =>
                {
                    b.HasOne("WmsResourcePlanner.Domain.Entities.Program", "Program")
                        .WithMany("Templates")
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Program");
                });

            modelBuilder.Entity("WmsResourcePlanner.Domain.Entities.TemplatePhase", b =>
                {
                    b.HasOne("WmsResourcePlanner.Domain.Entities.Template", "Template")
                        .WithMany("Phases")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("WmsResourcePlanner.Domain.Entities.Workstream", b =>
                {
                    b.HasOne("WmsResourcePlanner.Domain.Entities.Program", "Program")
                        .WithMany("Workstreams")
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Program");
                });

            modelBuilder.Entity("WmsResourcePlanner.Domain.Entities.FocusArea", b =>
                {
                    b.Navigation("ResourcePlanLines");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("WmsResourcePlanner.Domain.Entities.Person", b =>
                {
                    b.Navigation("ResourcePlanLines");
                });

            modelBuilder.Entity("WmsResourcePlanner.Domain.Entities.PlanningScenario", b =>
                {
                    b.Navigation("ResourcePlanLines");
                });

            modelBuilder.Entity("WmsResourcePlanner.Domain.Entities.Program", b =>
                {
                    b.Navigation("People");

                    b.Navigation("Roles");

                    b.Navigation("Scenarios");

                    b.Navigation("Sites");

                    b.Navigation("Teams");

                    b.Navigation("Templates");

                    b.Navigation("Workstreams");
                });

            modelBuilder.Entity("WmsResourcePlanner.Domain.Entities.Role", b =>
                {
                    b.Navigation("ResourcePlanLines");

                    b.Navigation("TeamRoles");
                });

            modelBuilder.Entity("WmsResourcePlanner.Domain.Entities.Site", b =>
                {
                    b.Navigation("TeamAssignments");
                });

            modelBuilder.Entity("WmsResourcePlanner.Domain.Entities.Team", b =>
                {
                    b.Navigation("ResourcePlanLines");

                    b.Navigation("SiteAssignments");

                    b.Navigation("TeamRoles");

                    b.Navigation("TemplateAssignments");
                });

            modelBuilder.Entity("WmsResourcePlanner.Domain.Entities.TeamTemplateAssignment", b =>
                {
                    b.Navigation("ResourcePlanLines");
                });

            modelBuilder.Entity("WmsResourcePlanner.Domain.Entities.Template", b =>
                {
                    b.Navigation("Phases");

                    b.Navigation("TeamAssignments");
                });

            modelBuilder.Entity("WmsResourcePlanner.Domain.Entities.TemplatePhase", b =>
                {
                    b.Navigation("ResourcePlanLines");
                });

            modelBuilder.Entity("WmsResourcePlanner.Domain.Entities.Workstream", b =>
                {
                    b.Navigation("FocusAreas");

                    b.Navigation("ResourcePlanLines");

                    b.Navigation("Teams");
                });
#pragma warning restore 612, 618
        }
    }
}
